name: CI/CD Pipeline Action Github

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: checkout action
        uses: actions/checkout@v4
        
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 24

      - name: install dependencies
        run: npm install

      - name: run the test
        run: npm test
